- name: users 
  hosts: all
  become: true
  tasks:
   - name: add user 'noc'
     user:
       name: noc
       state: present
       shell: /sbin/nologin
   - name: add user 'noc-2'
     user:
       name: nocv2
       state: present
       shell: /sbin/nologin
